version: "3.5"

services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - $EXPOSE_DB_PORT:$DB_PORT
    volumes:
      - data:/var/lib/postgresql/data

  app:
    container_name: balance-service
    build:
      context: "./"
    entrypoint: ./main
    depends_on:
      - db
    ports:
      - $PORT:$PORT
    restart: always

volumes:
  data: