DROP TABLE IF EXISTS service CASCADE;
DROP TABLE IF EXISTS reservation CASCADE;
DROP TABLE IF EXISTS replenishment CASCADE;
DROP TABLE IF EXISTS commit_reservation CASCADE;
DROP TYPE IF EXISTS reservation_status CASCADE;
DROP TABLE IF EXISTS balance CASCADE;
DROP VIEW IF EXISTS balance_history CASCADE;