// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/balance/": {
            "get": {
                "tags": [
                    "Balance"
                ],
                "summary": "Получение баланса пользователя",
                "operationId": "get-balance",
                "parameters": [
                    {
                        "description": "User ID",
                        "name": "user_id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/BalanceGetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Balance"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/AppError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/AppError"
                        }
                    },
                    "418": {
                        "description": "I'm a teapot",
                        "schema": {
                            "$ref": "#/definitions/AppError"
                        }
                    }
                }
            }
        },
        "/balance/reduce/": {
            "post": {
                "description": "В случае уменьшения баланса ранее не упомянутого пользователя, он НЕ создается в БД (возвращается 404)",
                "tags": [
                    "Balance"
                ],
                "summary": "Уменьшает баланс пользователя",
                "operationId": "reduce-balance",
                "parameters": [
                    {
                        "description": "User balance",
                        "name": "balance",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/BalanceChangeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/BalanceChangeRequest"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/AppError"
                        }
                    },
                    "418": {
                        "description": "I'm a teapot",
                        "schema": {
                            "$ref": "#/definitions/AppError"
                        }
                    }
                }
            }
        },
        "/balance/replenish/": {
            "post": {
                "description": "В случае пополнения баланса ранее не упомянутого пользователя, он создается в БД",
                "tags": [
                    "Balance"
                ],
                "summary": "Пополняет баланс пользователя",
                "operationId": "replenish-balance",
                "parameters": [
                    {
                        "description": "User balance",
                        "name": "balance",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/BalanceChangeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/BalanceChangeRequest"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/AppError"
                        }
                    },
                    "418": {
                        "description": "I'm a teapot",
                        "schema": {
                            "$ref": "#/definitions/AppError"
                        }
                    }
                }
            }
        },
        "/balance/transfer/": {
            "post": {
                "tags": [
                    "Balance"
                ],
                "summary": "Переводит деньги с одного счета на другой",
                "operationId": "transfer-balance",
                "parameters": [
                    {
                        "description": "Transfer money",
                        "name": "balance",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/TransferRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/AppError"
                        }
                    },
                    "418": {
                        "description": "I'm a teapot",
                        "schema": {
                            "$ref": "#/definitions/AppError"
                        }
                    }
                }
            }
        },
        "/history/": {
            "get": {
                "tags": [
                    "History"
                ],
                "summary": "Получение истории баланса пользователя",
                "operationId": "get-balance-history",
                "parameters": [
                    {
                        "description": "User ID",
                        "name": "user_id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/BalanceHistory"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/HistoryRow"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/AppError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/AppError"
                        }
                    },
                    "418": {
                        "description": "I'm a teapot",
                        "schema": {
                            "$ref": "#/definitions/AppError"
                        }
                    }
                }
            }
        },
        "/report/": {
            "post": {
                "description": "Отчет пересоздается только за текущий месяц",
                "tags": [
                    "Report"
                ],
                "summary": "Получение ссылки на сформированный отчет",
                "operationId": "get-report",
                "parameters": [
                    {
                        "description": "Report options",
                        "name": "report",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ReportRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ReportResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/AppError"
                        }
                    },
                    "418": {
                        "description": "I'm a teapot",
                        "schema": {
                            "$ref": "#/definitions/AppError"
                        }
                    }
                }
            }
        },
        "/reservation/cancel/": {
            "post": {
                "tags": [
                    "Reservation"
                ],
                "summary": "Отмена резервации денег за услугу",
                "operationId": "reservation-cancel",
                "parameters": [
                    {
                        "description": "Reservation",
                        "name": "reservation",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Reservation"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/AppError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/AppError"
                        }
                    },
                    "418": {
                        "description": "I'm a teapot",
                        "schema": {
                            "$ref": "#/definitions/AppError"
                        }
                    }
                }
            }
        },
        "/reservation/confirm/": {
            "post": {
                "tags": [
                    "Reservation"
                ],
                "summary": "Подтверждение списывания денег за услугу",
                "operationId": "reservation-confirm",
                "parameters": [
                    {
                        "description": "Reservation",
                        "name": "reservation",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Reservation"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/AppError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/AppError"
                        }
                    },
                    "418": {
                        "description": "I'm a teapot",
                        "schema": {
                            "$ref": "#/definitions/AppError"
                        }
                    }
                }
            }
        },
        "/reservation/reserve/": {
            "post": {
                "tags": [
                    "Reservation"
                ],
                "summary": "Резервация денег на услугу",
                "operationId": "reservation-reserve",
                "parameters": [
                    {
                        "description": "Reservation",
                        "name": "reservation",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Reservation"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/AppError"
                        }
                    },
                    "418": {
                        "description": "I'm a teapot",
                        "schema": {
                            "$ref": "#/definitions/AppError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "AppError": {
            "type": "object",
            "properties": {
                "developer_message": {
                    "description": "Сообщение для разработчика",
                    "type": "string"
                },
                "message": {
                    "description": "Сообщение",
                    "type": "string"
                }
            }
        },
        "Balance": {
            "type": "object",
            "required": [
                "balance",
                "user_id"
            ],
            "properties": {
                "balance": {
                    "description": "Баланс пользователя",
                    "type": "number",
                    "minimum": 0
                },
                "user_id": {
                    "description": "UUID баланса пользователя",
                    "type": "string"
                }
            }
        },
        "BalanceChangeRequest": {
            "type": "object",
            "required": [
                "amount",
                "user_id"
            ],
            "properties": {
                "amount": {
                    "description": "Баланс пользователя",
                    "type": "number"
                },
                "comment": {
                    "description": "Коментарий",
                    "type": "string"
                },
                "user_id": {
                    "description": "UUID баланса пользователя",
                    "type": "string",
                    "example": "7a13445c-d6df-4111-abc0-abb12f610069"
                }
            }
        },
        "BalanceGetRequest": {
            "type": "object",
            "required": [
                "user_id"
            ],
            "properties": {
                "user_id": {
                    "type": "string",
                    "example": "7a13445c-d6df-4111-abc0-abb12f610069"
                }
            }
        },
        "BalanceHistory": {
            "type": "object",
            "required": [
                "order_by",
                "order_field",
                "user_id"
            ],
            "properties": {
                "limit": {
                    "type": "integer",
                    "minimum": 0
                },
                "offset": {
                    "type": "integer",
                    "minimum": 0
                },
                "order_by": {
                    "description": "Порядок сортировки",
                    "type": "string",
                    "default": "desc",
                    "enum": [
                        "desc",
                        "asc"
                    ]
                },
                "order_field": {
                    "description": "Поле для сортировки",
                    "type": "string",
                    "default": "create_date",
                    "enum": [
                        "create_date",
                        "amount"
                    ]
                },
                "user_id": {
                    "description": "UUID баланса пользователя",
                    "type": "string",
                    "example": "7a13445c-d6df-4111-abc0-abb12f610069"
                }
            }
        },
        "HistoryRow": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "Сумма",
                    "type": "number"
                },
                "comment": {
                    "description": "Комментарий",
                    "type": "string"
                },
                "create_at": {
                    "description": "Время создания",
                    "type": "string"
                },
                "order_id": {
                    "description": "UUID заказа",
                    "type": "string"
                },
                "service_name": {
                    "description": "Название услуги",
                    "type": "string"
                },
                "transaction_type": {
                    "description": "Тип транзакции",
                    "type": "string"
                },
                "user_id_from": {
                    "description": "UUID отправителя",
                    "type": "string"
                },
                "user_id_to": {
                    "description": "UUID получателя",
                    "type": "string"
                }
            }
        },
        "ReportRequest": {
            "type": "object",
            "required": [
                "month",
                "year"
            ],
            "properties": {
                "month": {
                    "description": "UUID баланса пользователя",
                    "type": "integer",
                    "maximum": 12,
                    "minimum": 1,
                    "example": 11
                },
                "year": {
                    "description": "Баланс пользователя",
                    "type": "integer",
                    "minimum": 2000,
                    "example": 2022
                }
            }
        },
        "ReportResponse": {
            "type": "object",
            "required": [
                "file_url"
            ],
            "properties": {
                "file_url": {
                    "description": "Ссылка на скачивание файла",
                    "type": "string"
                }
            }
        },
        "Reservation": {
            "type": "object",
            "required": [
                "cost",
                "order_id",
                "service_id",
                "user_id"
            ],
            "properties": {
                "comment": {
                    "description": "Дополнительный комментарий",
                    "type": "string"
                },
                "cost": {
                    "description": "Стоимость услуги",
                    "type": "number"
                },
                "order_id": {
                    "description": "UUID заказа",
                    "type": "string",
                    "example": "983e8792-6736-41bd-9f1a-7c67f8501645"
                },
                "service_id": {
                    "description": "UUID сервиса",
                    "type": "string",
                    "example": "34e16535-480c-43f8-95a9-b7a503499af0"
                },
                "user_id": {
                    "description": "UUID баланса пользователя",
                    "type": "string",
                    "example": "7a13445c-d6df-4111-abc0-abb12f610069"
                }
            }
        },
        "TransferRequest": {
            "type": "object",
            "required": [
                "amount",
                "user_id_from",
                "user_id_to"
            ],
            "properties": {
                "amount": {
                    "description": "Списание",
                    "type": "number"
                },
                "comment": {
                    "description": "Коментарий",
                    "type": "string"
                },
                "user_id_from": {
                    "description": "UUID баланса отправителя",
                    "type": "string",
                    "example": "7a13445c-d6df-4111-abc0-abb12f610069"
                },
                "user_id_to": {
                    "description": "UUID баланса получателя",
                    "type": "string",
                    "example": "7a13445c-d6df-4111-abc0-abb12f610068"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "API User Balance Service",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
