// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/{user_id}": {
            "get": {
                "tags": [
                    "Balance"
                ],
                "summary": "Получение баланса пользователя",
                "operationId": "get-balance",
                "parameters": [
                    {
                        "type": "string",
                        "default": "7a13445c-d6df-4111-abc0-abb12f610069",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.GetBalanceResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.GetBalanceResponse": {
            "type": "object",
            "properties": {
                "balance": {
                    "description": "Баланс пользователя",
                    "type": "number"
                },
                "user_id": {
                    "description": "UUID баланса пользователя",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "/balance/",
	Schemes:          []string{},
	Title:            "Adapter API documentation",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
